[
    {
        "id":"31889",
        "title":"面—一个人的晚餐",
        "tags":"养胃;面;美味;漂亮;调理肠胃",
        "imtro":"记得小时候去亲戚家做客，他们做了非常美味的点心给我吃，到现在我还记忆犹新，里面有爽滑的方便面、青菜、胡萝卜、肉丝、青椒、黄瓜、鸡蛋做浇头。 昨天晚上老公吃我做的别的菜吃饱了，所以就不想吃，自己一个人也不知道吃什么，就做了个简单的面条，但味道非常棒，看去颜色也很漂亮的呢，呵呵~",
        "ingredients":"面条,50g;里脊肉,50g;胡萝卜丝,1/2个;青菜,100g;鸡蛋,1个",
        "burden":"油,适量;盐,适量;生抽,适量",
        "albums":[
            "http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/t/32/31889_505050.jpg"
        ],
        "steps":[
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_2ae449cc2630fd24.jpg",
                "step":"1.青菜白、胡萝卜肉切丝备用"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_8a1e060a112ba854.jpg",
                "step":"2.青菜叶切好备用"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_582f46d1827bf083.jpg",
                "step":"3.鸡蛋打散"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_f94c4f659b5770e9.jpg",
                "step":"4.先把鸡蛋炒好备用"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_44bf4e6268fe1851.jpg",
                "step":"5.再用剩余的底油加入肉丝胡萝卜丝翻炒"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_7c86d727ccbe6546.jpg",
                "step":"6.等软了后加入青菜丝盐，生抽调味。"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_43ca1389b9330e4e.jpg",
                "step":"7.最后出锅备用"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_8c11bebb9876122d.jpg",
                "step":"8.煮好面条，青菜叶在最后出锅前放"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/319/31889_ca1cdcbb9c82ea5f.jpg",
                "step":"9.最后加上浇头即可食用"
            }
        ]
    },
    {
        "id":"44264",
        "title":"懒人晚餐之瘦肉粥",
        "tags":"早餐;健忘;冬季;电饭锅;养生粥;益智;健脑益智;健脑;增强记忆力",
        "imtro":"每天都要想着晚上要炒什么菜，干脆就直接做瘦肉粥算了。我特别感谢我的婆婆，她从来不会说，这道菜怎么煮的这么难吃，我不吃之类的话。记得第一次学着做瘦肉粥的时候，一开锅，婆婆就说好香啊！端出来婆婆吃的第一口，又大赞了说好吃好吃！",
        "ingredients":"大米,50g;瘦肉,100g;虾仁,适量;干贝,适量;大白菜,半颗",
        "burden":"油,适量;盐,适量;鸡精,适量",
        "albums":[
            "http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/t/45/44264_463061.jpg"
        ],
        "steps":[
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_5a5b700305e4447f.jpg",
                "step":"1.材料备齐，虾仁和干贝提前泡十分钟"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_e2771e813e89c665.jpg",
                "step":"2.大米洗净下锅"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_0989291245fd57ac.jpg",
                "step":"3.倒入干贝和虾仁"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_bc144cde98e69495.jpg",
                "step":"4.再倒入瘦肉（瘦肉用开水焯过）"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_5a270806fb2bc8d2.jpg",
                "step":"5.再加入盐"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_7bb99554278c40f5.jpg",
                "step":"6.倒入适量的水"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_85b613d288e70195.jpg",
                "step":"7.盖上盖子，按下煮粥的键"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_ac3bf6753a61e219.jpg",
                "step":"8.30分钟排气完了，再下大白菜"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/443/44264_7821b6f71e44f148.jpg",
                "step":"9.再倒些油和鸡精进去就可以了"
            }
        ]
    },
    {
        "id":"64762",
        "title":"一个人的晚餐--荷包蛋汤面",
        "tags":"家常菜",
        "imtro":"一个人在家就懒得做饭，工作一天有点累了但是不愿动弹。可也不能委屈了自己的肚子啊，于是进厨房翻翻有啥能吃的，还剩下一袋方便面就煮面了。",
        "ingredients":"挂面,50g;方便面,1袋",
        "burden":"西红柿,1个;鸡蛋,1个",
        "albums":[
            "http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/t/65/64762_854699.jpg"
        ],
        "steps":[
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_d234e9f21d54f36b.jpg",
                "step":"1.准备好食材"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_c938b7e20e0bfc38.jpg",
                "step":"2.西红柿洗净切块"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_1b0a4a94adf5d65b.jpg",
                "step":"3.锅中放入清水和西红柿块，大火烧开"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_6fdf4190ec8035d9.jpg",
                "step":"4.水开后打入鸡蛋煮一会"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_112462212aea4c20.jpg",
                "step":"5.放入挂面，一袋方便面吃不饱的"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_92aef4dfc535347d.jpg",
                "step":"6.将挂面煮2分钟左右"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_34656955e81ba014.jpg",
                "step":"7.放入方便面煮熟"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_39346fe5b07c7eb0.jpg",
                "step":"8.关火，放入调味料"
            },
            {
                "img":"http://juheimg.oss-cn-hangzhou.aliyuncs.com/cookbook/s/648/64762_e486dbd5b0c936e3.jpg",
                "step":"9.盛入碗中就可以吃喽"
            }
        ]
    }
]